### ISSUE TITLE
Change Project Name

### ISSUE THREAD

**Issue by nikkipantony** [nikkipantony/ally-starter-kit#9]
## Need to change project name to: Ally Gatsby Starter Kit

**Tasks:**
- [x] Update project title
- [x] Update description
- [x] Update README
- [x] Update config files
- [ ] Update page content

**Comment by nikkipantony** [comment]
`Update page content` not completed - New ticket created for task to be carried out at a later date after other work has first be completed. #37

**Comment by nikkipantony** [comment]
Completed. 

Only one outstanding task `Update page content`

- New ticket created for task to be carried out at a later date after other work has first be completed. #37
